using Tasks;
BoardManager boardManager = new BoardManager();
boardManager.addBoard(new Board("my board"));
boardManager.addBoard(new Board("my other board"));
boardManager.addBoard(new Board("my third board"));
boardManager._boards[0].addTask(new Tasks.Task("wash dishes"));
boardManager._boards[0].addTask(new Tasks.Task("do laundry"));
boardManager._boards[0].addTask(new Tasks.Task("take out bins"));
boardManager._boards[0].addTask(new Tasks.Task("grow as a person"));
ProgramOpen menus = new ProgramOpen(boardManager);
menus.OnSelect();
